const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const source = fs.readFileSync(path.resolve(__dirname, '..', 'scripts', 'script.js'), 'utf8');
const html = fs.readFileSync(path.resolve(__dirname, '..', 'index.html'), 'utf8');
const css = fs.readFileSync(path.resolve(__dirname, '..', 'style', 'style.css'), 'utf8');

assert.match(source, /let showNodeTransactionsChronologically = false/);
assert.match(source, /id="chronological-transactions-toggle"/);
assert.match(source, /function setNodeTransactionsChronological\(enabled\)/);
assert.match(source, /function renderChronologicalNodeTransactions\(visibleEdges, node\)/);
assert.match(source, /function sortNodeTransactions\(items, node\)/);
assert.match(source, /function setNodeTransactionSort\(column\)/);
assert.match(source, /NODE_TRANSACTION_SORT_STORAGE_KEY/);
assert.match(source, /renderSortableTransactionHeader\("timestamp", "Timestamp"/);
assert.match(source, /aria-sort=/);
assert.match(source, /function getNodeTransactionDirection\(tx, node\)/);
assert.match(source, /formatSignedNodeTransactionAmount\(tx, node\)/);
assert.match(source, /sortNodeTransactions\(interactions, node\)/);
assert.match(source, /Show all transactions chronologically/);
assert.match(source, /const NODE_TRANSACTION_PAGE_SIZE = 100/);
assert.match(source, /const renderedOperations = operations\.slice\(0, nodeTransactionRenderLimit\)/);
assert.match(source, /function getPaginatedNodeEdges\(visibleEdges, node\)/);
assert.match(source, /\.slice\(0, nodeTransactionRenderLimit\)\.map\(item => item\.edge\)/);
assert.match(source, /function showMoreNodeTransactions\(\)/);
assert.match(source, /Showing \$\{shown\.toLocaleString\(\)\} of \$\{total\.toLocaleString\(\)\} operations/);
assert.match(source, /renderNodeTransactionLoadMore\(visibleEdges\.length\)/);
assert.doesNotMatch(source, /console\.log\("Tx Hash:/);
assert.match(source, /Linked Node/);
assert.match(html, /id="transaction-memo-popup"[\s\S]*?id="transaction-memo-content"/);
assert.match(source, /function setupTransactionMemoTouch\(\)/);
assert.match(source, /event\.pointerType !== "touch"/);
assert.match(source, /\.transaction-memo-trigger/);
assert.match(source, /Math\.hypot\(event\.clientX - x, event\.clientY - y\) > 10/);
assert.match(source, /document\.addEventListener\("pointerdown"[\s\S]*?closeTransactionMemoPopup\(\);[\s\S]*?}, true\);/);
assert.match(source, /dismissingPointerId === event\.pointerId/);
assert.match(css, /\.transaction-memo-popup\s*\{[\s\S]*?z-index: var\(--z-modal\);/);

const addressHelper = source.match(/function addressesMatchForTransaction\(left, right\) \{[\s\S]*?\n\}/)?.[0];
const directionHelper = source.match(/function getNodeTransactionDirection\(tx, node\) \{[\s\S]*?\n\}/)?.[0];
assert.ok(addressHelper && directionHelper, 'Transaction direction helpers should exist');
const context = {};
require('node:vm').runInNewContext(`${addressHelper}; ${directionHelper}; result = getNodeTransactionDirection;`, context);
assert.equal(context.result({ sender_key: 'B62sender', receiver_key: 'B62receiver' }, 'B62sender'), -1);
assert.equal(context.result({ sender_key: 'B62sender', receiver_key: 'B62receiver' }, 'B62receiver'), 1);
assert.equal(context.result({ sender_key: '0xABC', receiver_key: '0xDEF' }, '0xabc'), -1);
assert.equal(context.result({ sender_key: 'tz1self', receiver_key: 'tz1self' }, 'tz1self'), 0);
assert.equal(context.result({ sender_key: 'sender', receiver_key: 'receiver' }, 'unknown'), null);

console.log('Chronological details tests passed');
