const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const sigma = fs.readFileSync(path.join(root, 'scripts', 'sigma.umd.js'), 'utf8');
const script = fs.readFileSync(path.join(root, 'scripts', 'script.js'), 'utf8');
const worker = fs.readFileSync(path.join(root, 'service-worker.js'), 'utf8');

assert.match(sigma, /previousPixelRatio = this\.pixelRatio/);
assert.match(sigma, /previousPixelRatio === this\.pixelRatio/);
assert.match(sigma, /function useMobileChromiumWebGLCompatibility\(/);
assert.match(sigma, /EdgA\\\//);
assert.match(sigma, /devicePixelRatio \|\| 1\) >= 3/);
assert.match(sigma, /if \(!useMobileChromiumWebGLCompatibility\(\)\) context = canvas\.getContext\("webgl2"/);
assert.doesNotMatch(sigma, /this\.width \* this\.pixelRatio \+ "px"/);
assert.match(sigma, /if \(currentTexture\) \{[\s\S]*?gl\.clear\(gl\.COLOR_BUFFER_BIT\);[\s\S]*?return this;/);
assert.match(sigma, /gl\.deleteTexture\(currentTexture\);\s*this\.textures\[_id2\] = null;/);
assert.match(sigma, /if \(!useMobileChromiumWebGLCompatibility\(\)\) _this\.createWebGLContext\("hoverNodes"\)/);
assert.match(sigma, /if \(!useMobileChromiumWebGLCompatibility\(\)\) \{\s*this\.nodeHoverPrograms\[key\] = new/);
assert.match(sigma, /if \(useMobileChromiumWebGLCompatibility\(\)\) \{\s*_this8\.render\(\)/);
assert.match(sigma, /if \(!useMobileChromiumWebGLCompatibility\(\)\) \{\s*_this\.createWebGLContext\("edges"/);
assert.match(sigma, /compatibilityMode \? this\.webGLContexts\.nodes : this\.webGLContexts\.edges/);
assert.match(sigma, /if \(useMobileChromiumWebGLCompatibility\(\) && \(!this\.settings\.hideEdgesOnMove \|\| !moving\)\)/);
assert.match(sigma, /if \(useMobileChromiumWebGLCompatibility\(\)\) \{\s*drawDiscNodeLabel\(context, data, settings\);\s*return;/);
assert.match(sigma, /if \(compatibilityMode && _this7\.displayedNodeLabels\.has\(node\)\) return;/);
assert.match(sigma, /if \(compatibilityMode\) return this;/);
assert.match(sigma, /_defineProperty\(_this, "hadMultiTouch", false\)/);
assert.match(sigma, /if \(touches\.length > 1\) this\.hadMultiTouch = true/);
assert.match(sigma, /if \(!e\.touches\.length && !this\.hadMultiTouch\)/);
assert.match(sigma, /if \(!e\.touches\.length\) this\.hadMultiTouch = false/);
assert.doesNotMatch(script, /scheduleSigmaViewportSync/);
assert.doesNotMatch(script, /reduceSigmaPixelRatioAfterContextLoss/);
assert.match(script, /webglcontextlost/);
assert.match(script, /webglcontextrestored/);
assert.match(script, /function rebuildSigmaRendererAfterContextLoss\(/);
assert.match(script, /renderer = new Sigma\(graph, container, settings\)/);
assert.match(script, /failedRenderer\.getCamera\(\)\.getState\(\)/);
assert.match(script, /sigmaWebGlLossIncidents/);
assert.match(script, /sigmaWebGlRecoveries/);
assert.match(script, /waitForSigmaWebGlRestoration/);
assert.match(script, /failedRenderer\.webGLContexts = \{\}/);
assert.match(script, /sigmaRecoverySnapshot/);
assert.match(script, /sigmaRecoveryLastError/);
assert.match(script, /WebGL1 compatibility/);
assert.match(script, /collectSigmaRenderingDiagnostics/);
assert.match(worker, /'\/scripts\/sigma\.umd\.js'/);

console.log('Sigma rendering resilience tests passed');
