const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const html = fs.readFileSync(path.resolve(__dirname, "..", "index.html"), "utf8");
const wallets = fs.readFileSync(path.resolve(__dirname, "..", "scripts", "walletconnect-donations.js"), "utf8");
const donations = fs.readFileSync(path.resolve(__dirname, "..", "scripts", "donations.js"), "utf8");
const app = fs.readFileSync(path.resolve(__dirname, "..", "scripts", "script.js"), "utf8");
const css = fs.readFileSync(path.resolve(__dirname, "..", "style", "style.css"), "utf8");
const worker = fs.readFileSync(path.resolve(__dirname, "..", "service-worker.js"), "utf8");

assert.match(html, /src="\.\/scripts\/walletconnect-donations\.bundle\.js"/);
assert.match(html, /id="wallet-connect-modal"[^>]+role="dialog"[^>]+hidden/);
assert.match(html, /id="wallet-connect-qr"/);
assert.match(html, /id="wallet-connect-copy"/);
assert.match(wallets, /e7c987c4886cb9b77abbda154818712e/);
assert.match(wallets, /eip6963:announceProvider/);
assert.match(wallets, /eip6963:requestProvider/);
assert.match(wallets, /window\.ethereum/);
assert.match(wallets, /requiredNamespaces:[\s\S]*?mina:/);
assert.match(wallets, /mina_sendPayment/);
assert.match(wallets, /showQrModal: false/);
assert.match(wallets, /import EthereumProvider from "@walletconnect\/ethereum-provider"/);
assert.match(wallets, /await sleep\(750\)/);
assert.match(wallets, /minaSessionRestored/);
assert.match(wallets, /customStoragePrefix: "minagraph-mina"/);
assert.match(wallets, /customStoragePrefix: `minagraph-evm-\$\{chainId\}`/);
assert.match(wallets, /url: window\.location\.origin/);
assert.match(wallets, /session_request_sent/);
assert.match(wallets, /publishing mina_sendPayment/);
assert.match(wallets, /params:\s*\{\s*from,/);
assert.match(wallets, /fee: String\(args\.fee \|\| "0\.01"\)/);
assert.match(wallets, /session approved/);
assert.match(wallets, /includes\("eth_sendTransaction"\)/);
assert.match(wallets, /evmProviderPromise/);
assert.match(wallets, /minaSessionSupports/);
assert.match(wallets, /Reconnect restored wallet/);
assert.match(wallets, /Wallet signature request timed out/);
assert.match(wallets, /ethereum-rpc\.publicnode\.com/);
assert.match(wallets, /bsc-dataseed\.bnbchain\.org/);
assert.match(wallets, /polygon-bor-rpc\.publicnode\.com/);
assert.match(wallets, /display_uri/);
assert.match(wallets, /metamask\.app\.link\/wc/);
assert.match(wallets, /link\.trustwallet\.com\/wc/);
assert.match(wallets, /aurowallet:\/\/wc/);
assert.match(donations, /MinagraphWallets\.connectEvmProvider\(connectionChainId\)/);
assert.match(donations, /method: "eth_sendTransaction"/);
assert.match(donations, /gas: "0x5208"/);
assert.match(donations, /confirmation lookup failed/);
assert.match(donations, /balanceOf\(address owner\)/);
assert.match(donations, /Insufficient \$\{token\} balance/);
assert.match(donations, /wallet_switchEthereumChain/);
assert.match(html, /id="donation-network"/);
assert.match(app, /MinagraphWallets\.getMinaProvider\(injectedProvider\)/);
assert.match(css, /\.wallet-connect-modal\s*\{/);
assert.match(css, /\.wallet-connect-card \[hidden\]\s*\{[\s\S]*?display: none !important/);
assert.match(worker, /mina-graph-explorer-v65/);
assert.match(worker, /\/scripts\/walletconnect-donations\.bundle\.js/);

console.log("WalletConnect donation tests passed");
